[build-system]
requires = [
    "setuptools>=80.9.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "docassemble.VTSuperiorCourtDebtAnswer"
version = "1.0"
description = "Superior Court debt answer interview for Vermont"
readme = "README.md"
authors = [
    { name = "Legal Services Vermont and Lemma Legal", email = "ksurette@legalservicesvt.org" },
]
dependencies = [
    "docassemble.ALToolbox @ git+https://github.com/SuffolkLITLab/docassemble-ALToolbox.git@main",
    "docassemble.AssemblyLine @ git+https://github.com/SuffolkLITLab/docassemble-AssemblyLine.git@main",
    "docassemble.VTCertificateOfServiceGeneral @ git+https://github.com/LSVermont/docassemble-VTCertificateOfServiceGeneral.git@main",
    "docassemble.VTDisclosureOfExemptIncome @ git+https://github.com/LSVermont/docassemble-VTDisclosureOfExemptIncome.git@main",
    "docassemble.VTFeeWaiverWithIncludeYMLFile @ git+https://github.com/VTskier/docassemble-VTFeeWaiverWithIncludeYMLFile.git@main",
    "docassemble.VTFinancialDisclosure @ git+https://github.com/LSVermont/docassemble-VTFinancialDisclosure.git@main",
    "docassemble.VTNoticeOfAppearance @ git+https://github.com/LSVermont/docassemble-VTNoticeOfAppearance.git@main",
    "docassemble.VTSharedYMLFile @ git+https://github.com/LSVermont/docassemble-VTSharedYMLFile.git@main",
]
license = "MIT"
license-files = [
    "LICENSE",
]

[project.urls]
Homepage = "https://VTLawHelp.org"

[tool.setuptools.packages.find]
where = [
    ".",
]
